# happydroid B1 (23 DOF) robot configuration for SONIC.
#
# PROVENANCE -- everything here traces back to the happydroid mjlab repo
# (github.com/happydroid-ai/mjlab_happydroid):
#   * The MJCF is ``research/wbc_b1/gmr/b1_retarget.xml``, itself GENERATED by
#     ``research/wbc_b1/gmr/make_retarget_xml.py`` from the real robot model
#     ``src/hd_mjlab/assets/robots/happydroid_B1_dd/xmls/happy_v1_direct_drive.xml``.
#   * Motor envelopes come from ``src/hd_mjlab/actuator/motor_specs.py`` (dyno-measured).
#   * PD gains are the "ARCHIVE walk" set from ``hdb1_constants.py`` -- these are
#     validated on hardware, NOT re-derived from the natural-frequency formula the
#     G1/H2 configs use. Do not "fix" them to match g1.py's ARMATURE * omega**2 style.
#   * The home pose mirrors ``hdb1_constants._home_joint_pos()``.
# Regenerate the asset after any CAD change; do not hand-edit mjcf/b1.xml.
#
# TWO DELIBERATE APPROXIMATIONS vs the real robot -- read before trusting sim2real:
#
# 1. ANKLE FOUR-BAR COLLAPSED. On hardware each ankle is driven by a motor through a
#    crank/coupler/rocker four-bar; ``*_Ankle_Ry`` is PASSIVE and the policy commands
#    ``*_Ankle_Motor``. URDF/USD and PhysX articulations cannot carry the closed loop,
#    so we use the collapsed tree: one direct-drive ``*_Ankle_Ry`` hinge. The linkage is
#    near 1:1 -- r = d(theta_motor)/d(theta_ankle) computed from
#    ``ankle_linkage_kin.ankle_to_motor`` is 1.0046 at the home pose and spans
#    0.69 (+30 deg, toe-down) .. 1.06 (-30 deg) across the joint range. So a constant
#    reflection at r ~= 1.0 OVER-estimates available ankle torque by up to ~31% at the
#    toe-down extreme. Policies trained here must be replayed through
#    ``gmr/expand_ankles.py`` (23-joint -> 27-joint, four-bar solved) before they touch
#    the robot.
# 2. IMPLICIT PD, NOT A DC MOTOR. mjlab drives B1 with ``DcMotorActuatorCfg`` -- PD on
#    top of a torque/speed envelope with latency domain randomization. SONIC's pipeline
#    assumes ``ImplicitActuatorCfg`` (its action scale and the C++ deploy stack both
#    depend on it), so the velocity-dependent torque rolloff and the latency DR are
#    LOST here. Expect sim to be optimistic at high joint speed.

from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg
import isaaclab.sim as sim_utils

ASSET_DIR = "gear_sonic/data/assets"

_DEG = 3.141592653589793 / 180.0

# --- motor envelopes (mjlab motor_specs.py, dyno-measured) -----------------------
# Joint-side reflected rotor inertia (kg*m^2).
ARMATURE_S1 = 0.0027360850830214357  # size 1: neck, forearm roll, wrist
ARMATURE_S2 = 0.00195  # size 2: shoulders
ARMATURE_S2E = ARMATURE_S2 * (32.0 / 14.0) ** 2  # size 2 + 14T->32T elbow belt
ARMATURE_S3 = 0.0083  # size 3: hip yaw, torso yaw, ankle motor
ARMATURE_S4 = 0.04885  # size 4: hip roll/pitch, knee

# Ankle: size-3 rotor inertia reflected onto the ankle axis through the four-bar
# (r ~= 1.0046 at home) plus the 0.002 structural armature the MJCF puts on the
# passive joint. See approximation (1) above.
ARMATURE_ANKLE = ARMATURE_S3 * 1.0046**2 + 0.002

# No-load speeds (rad/s) -> velocity_limit_sim.
VEL_S2 = 15.9
VEL_S2E = VEL_S2 / (32.0 / 14.0)
VEL_S3 = 15.5
VEL_S4 = 8.97
VEL_S1 = 20.0  # mjlab models these with a flat clamp and no speed limit; nominal

# --- PD gains: the hardware-validated "ARCHIVE walk" set ------------------------
# mjlab exposes these as HDB1_KP_SCALE_* env knobs; these are the unscaled defaults.
STIFFNESS_SHOULDER, DAMPING_SHOULDER = 25.0, 1.8
STIFFNESS_ELBOW, DAMPING_ELBOW = 25.0, 1.8
STIFFNESS_S3, DAMPING_S3 = 35.0, 4.0  # hip yaw + torso yaw
STIFFNESS_ANKLE, DAMPING_ANKLE = 35.0, 4.0  # split from S3 so the light ankle tunes apart
STIFFNESS_S4, DAMPING_S4 = 45.0, 5.0  # hip roll/pitch + knee
STIFFNESS_S1, DAMPING_S1 = 72.0, 3.0  # neck, forearm roll, wrist

# --- home pose (hdb1_constants._home_joint_pos, four-bar branch collapsed) -------
_HOME_KNEE = 39.2 * _DEG
_HOME_HIP_RY = 21.0 * _DEG
_HOME_ANKLE = 19.0 * _DEG
_HOME_SHOULDER_RX = 10.0 * _DEG
_HOME_ELBOW = 30.0 * _DEG
_HOME_HIP_RX = 2.0 * _DEG

# --- ordering ---------------------------------------------------------------------
# MuJoCo orders the tree depth-first (XML document order); PhysX/IsaacLab orders it
# breadth-first (level order). Both lists below were derived mechanically from
# mjcf/b1.xml and the index arrays round-trip (verified at generation time), so do not
# hand-edit them -- regenerate if the kinematic tree changes.
#
# NOTE: B1 is TORSO-rooted. The free joint is on ``hdb1_torso_contoured`` and the
# pelvis hangs off it via ``Torso_Rz``. G1 is the other way round (pelvis-rooted), so
# body index 0 here is the torso, not the pelvis, and motion-PKL root_trans_offset /
# root_rot refer to the TORSO frame.
#
# This forces the tracking anchor: ``motion_lib_base.py`` asserts
# ``anchor_body_idx_full == 0 and body_indexes[0] == 0``, so the anchor MUST be the root
# body and MUST lead ``body_names``. sonic_b1.yaml therefore anchors on the TORSO where
# the G1 configs anchor on the pelvis. Root != anchor is not supported.

# Body names, IsaacLab (BFS) order, root at index 0. Named *_JOINTS to match the
# g1.py/h2.py convention that ``robot_mapping`` and the order converters expect.
B1_ISAACLAB_JOINTS = [
    "hdb1_torso_contoured",
    "hdb1_pelvis_large",
    "hdb1_neck_ext",
    "hdb1_right_shoulder",
    "hdb1_left_shoulder",
    "hdb1_right_hip_rot",
    "hdb1_left_hip_rot",
    "hdb1_head",
    "hdb1_right_upper_arm",
    "hdb1_left_upper_arm",
    "hdb1_right_hip_ext",
    "hdb1_left_hip_ext",
    "hdb1_right_forearm_rot",
    "hdb1_left_forearm_rot",
    "hdb1_right_upper_leg",
    "hdb1_left_upper_leg",
    "hdb1_right_forearm",
    "hdb1_left_forearm",
    "hdb1_right_lower_leg",
    "hdb1_left_lower_leg",
    "hdb1_right_hand_fixed",
    "hdb1_left_hand_fixed",
    "hdb1_right_foot",
    "hdb1_left_foot",
]

B1_MUJOCO_BODIES = [
    "hdb1_torso_contoured",
    "hdb1_pelvis_large",
    "hdb1_right_hip_rot",
    "hdb1_right_hip_ext",
    "hdb1_right_upper_leg",
    "hdb1_right_lower_leg",
    "hdb1_right_foot",
    "hdb1_left_hip_rot",
    "hdb1_left_hip_ext",
    "hdb1_left_upper_leg",
    "hdb1_left_lower_leg",
    "hdb1_left_foot",
    "hdb1_neck_ext",
    "hdb1_head",
    "hdb1_right_shoulder",
    "hdb1_right_upper_arm",
    "hdb1_right_forearm_rot",
    "hdb1_right_forearm",
    "hdb1_right_hand_fixed",
    "hdb1_left_shoulder",
    "hdb1_left_upper_arm",
    "hdb1_left_forearm_rot",
    "hdb1_left_forearm",
    "hdb1_left_hand_fixed",
]

# Actuated joint names in each convention. Joint i drives body i+1 in the same
# ordering -- the invariant IsaacLabMuJoCoConverter.convert() relies on to reuse
# DOF_MAPPINGS for per-body transforms. Verified at generation time for both orders.
B1_ISAACLAB_DOF_NAMES = [
    "Torso_Rz",
    "Neck_Rz",
    "R_Shoulder_Rx",
    "L_Shoulder_Rx",
    "R_Hip_Rx",
    "L_Hip_Rx",
    "Neck_Ry",
    "R_Shoulder_Ry",
    "L_Shoulder_Ry",
    "R_Hip_Rz",
    "L_Hip_Rz",
    "R_Elbow_Ry",
    "L_Elbow_Ry",
    "R_Hip_Ry",
    "L_Hip_Ry",
    "R_Forearm_Rz",
    "L_Forearm_Rz",
    "R_Knee_Ry",
    "L_Knee_Ry",
    "R_Wrist_Rx",
    "L_Wrist_Rx",
    "R_Ankle_Ry",
    "L_Ankle_Ry",
]

# Actuated joint names, MuJoCo (DFS) order.
B1_MUJOCO_DOF_NAMES = [
    "Torso_Rz",
    "R_Hip_Rx",
    "R_Hip_Rz",
    "R_Hip_Ry",
    "R_Knee_Ry",
    "R_Ankle_Ry",
    "L_Hip_Rx",
    "L_Hip_Rz",
    "L_Hip_Ry",
    "L_Knee_Ry",
    "L_Ankle_Ry",
    "Neck_Rz",
    "Neck_Ry",
    "R_Shoulder_Rx",
    "R_Shoulder_Ry",
    "R_Elbow_Ry",
    "R_Forearm_Rz",
    "R_Wrist_Rx",
    "L_Shoulder_Rx",
    "L_Shoulder_Ry",
    "L_Elbow_Ry",
    "L_Forearm_Rz",
    "L_Wrist_Rx",
]

B1_ISAACLAB_TO_MUJOCO_DOF = [
    0, 4, 9, 13, 17, 21, 5, 10, 14, 18, 22, 1,
    6, 2, 7, 11, 15, 19, 3, 8, 12, 16, 20,
]

B1_MUJOCO_TO_ISAACLAB_DOF = [
    0, 11, 13, 18, 1, 6, 12, 14, 19, 2, 7, 15,
    20, 3, 8, 16, 21, 4, 9, 17, 22, 5, 10,
]

B1_ISAACLAB_TO_MUJOCO_BODY = [
    0, 1, 5, 10, 14, 18, 22, 6, 11, 15, 19, 23,
    2, 7, 3, 8, 12, 16, 20, 4, 9, 13, 17, 21,
]

B1_MUJOCO_TO_ISAACLAB_BODY = [
    0, 1, 12, 14, 19, 2, 7, 13, 15, 20, 3, 8,
    16, 21, 4, 9, 17, 22, 5, 10, 18, 23, 6, 11,
]

B1_ISAACLAB_TO_MUJOCO_MAPPING = {
    "isaaclab_joints": B1_ISAACLAB_JOINTS,
    "isaaclab_to_mujoco_dof": B1_ISAACLAB_TO_MUJOCO_DOF,
    "mujoco_to_isaaclab_dof": B1_MUJOCO_TO_ISAACLAB_DOF,
    "isaaclab_to_mujoco_body": B1_ISAACLAB_TO_MUJOCO_BODY,
    "mujoco_to_isaaclab_body": B1_MUJOCO_TO_ISAACLAB_BODY,
}

# Effort limits are the MJCF ``actuatorfrcrange`` clamps, which is what mjlab's
# validated MuJoCo policies actually operated under. motor_specs' dyno peak torques are
# HIGHER for some clusters (s4 peak 61 Nm vs the 45 Nm clamp on hip/knee, s3 31 vs 37 on
# hip yaw/torso), and in MuJoCo the joint clamp binds first. If you want the optimistic
# envelope instead, swap these for s*_peak_torque -- but retune before deploying.
B1_CFG = ArticulationCfg(
    spawn=sim_utils.MjcfFileCfg(
        asset_path=f"{ASSET_DIR}/robot_description/mjcf/b1.xml",
        fix_base=False,
        self_collision=True,
        import_physics_scene=False,
        activate_contact_sensors=True,
        collision_type="Convex Hull",
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=True,
            solver_position_iteration_count=8,
            solver_velocity_iteration_count=4,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        # Derived, not nominal. The MJCF's carried-over 0.9 left the soles floating
        # 1.92 cm above z=0. Forward kinematics over the home pose puts the lowest foot
        # mesh vertex at +0.0192 m, so 0.9 - 0.0192 = 0.8808 rests them exactly on the
        # ground; +2 mm of clearance avoids first-frame interpenetration (the same
        # reason G1 spawns slightly high). Equivalent to mjlab's compute_home_z().
        # Re-derive with scripts/preview_b1.py if the home pose or foot mesh changes.
        pos=(0.0, 0.0, 0.8828),
        joint_pos={
            "Torso_Rz": 0.0,
            "Neck_Rz": 0.0,
            "Neck_Ry": 0.0,
            "R_Hip_Rx": -_HOME_HIP_RX,
            "L_Hip_Rx": _HOME_HIP_RX,
            ".*_Hip_Rz": 0.0,
            ".*_Hip_Ry": -_HOME_HIP_RY,
            ".*_Knee_Ry": _HOME_KNEE,
            ".*_Ankle_Ry": -_HOME_ANKLE,
            "R_Shoulder_Rx": -_HOME_SHOULDER_RX,
            "L_Shoulder_Rx": _HOME_SHOULDER_RX,
            ".*_Shoulder_Ry": 0.0,
            ".*_Elbow_Ry": -_HOME_ELBOW,
            ".*_Forearm_Rz": 0.0,
            ".*_Wrist_Rx": 0.0,
        },
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.9,
    actuators={
        "legs": ImplicitActuatorCfg(
            joint_names_expr=[".*_Hip_Rx", ".*_Hip_Ry", ".*_Knee_Ry"],
            effort_limit_sim=45.0,
            velocity_limit_sim=VEL_S4,
            stiffness=STIFFNESS_S4,
            damping=DAMPING_S4,
            armature=ARMATURE_S4,
        ),
        "hip_yaw": ImplicitActuatorCfg(
            joint_names_expr=[".*_Hip_Rz"],
            effort_limit_sim=37.0,
            velocity_limit_sim=VEL_S3,
            stiffness=STIFFNESS_S3,
            damping=DAMPING_S3,
            armature=ARMATURE_S3,
        ),
        "torso": ImplicitActuatorCfg(
            joint_names_expr=["Torso_Rz"],
            effort_limit_sim=37.0,
            velocity_limit_sim=VEL_S3,
            stiffness=STIFFNESS_S3,
            damping=DAMPING_S3,
            armature=ARMATURE_S3,
        ),
        "feet": ImplicitActuatorCfg(
            joint_names_expr=[".*_Ankle_Ry"],
            effort_limit_sim=31.0,  # motor 31 Nm x linkage r ~= 1.0; see approximation (1)
            velocity_limit_sim=VEL_S3,
            stiffness=STIFFNESS_ANKLE,
            damping=DAMPING_ANKLE,
            armature=ARMATURE_ANKLE,
        ),
        "shoulders": ImplicitActuatorCfg(
            joint_names_expr=[".*_Shoulder_Rx", ".*_Shoulder_Ry"],
            effort_limit_sim=16.0,
            velocity_limit_sim=VEL_S2,
            stiffness=STIFFNESS_SHOULDER,
            damping=DAMPING_SHOULDER,
            armature=ARMATURE_S2,
        ),
        "elbows": ImplicitActuatorCfg(
            joint_names_expr=[".*_Elbow_Ry"],
            effort_limit_sim=36.57,
            velocity_limit_sim=VEL_S2E,
            stiffness=STIFFNESS_ELBOW,
            damping=DAMPING_ELBOW,
            armature=ARMATURE_S2E,
        ),
        "wrists": ImplicitActuatorCfg(
            joint_names_expr=[".*_Forearm_Rz", ".*_Wrist_Rx"],
            effort_limit_sim={".*_Forearm_Rz": 2.5, ".*_Wrist_Rx": 7.5},
            velocity_limit_sim=VEL_S1,
            stiffness=STIFFNESS_S1,
            damping=DAMPING_S1,
            armature=ARMATURE_S1,
        ),
        "neck": ImplicitActuatorCfg(
            joint_names_expr=["Neck_Rz", "Neck_Ry"],
            effort_limit_sim=2.5,
            velocity_limit_sim=VEL_S1,
            stiffness=STIFFNESS_S1,
            damping=DAMPING_S1,
            armature=ARMATURE_S1,
        ),
    },
)

# Same 0.25 * effort / stiffness rule the G1 config uses.
#
# WARNING -- the size-1 cluster comes out nearly frozen. With effort 2.5 Nm against
# kp 72, Neck_* and *_Forearm_Rz get scale 0.0087, i.e. ~0.5 deg of authority at a
# full-scale action; *_Wrist_Rx gets 0.026. For comparison the big joints land at
# 0.16-0.37, right alongside G1's hip (0.35), and even G1's weakest joint (wrist pitch)
# is 0.0745 -- 8.5x more than B1's neck. So the policy effectively cannot use the neck
# or forearm roll as configured.
#
# This is a consequence of pairing the MJCF's physical actuatorfrcrange with mjlab's
# firmware kp. mjlab avoids it by giving that cluster effort_limit=500 -- an intentional
# flat clamp, not a real torque. Two honest fixes, both needing a retune:
#   (a) lower STIFFNESS_S1 (the 0.5 deg is the kp's fault as much as the torque's), or
#   (b) follow mjlab and raise the size-1 effort limit, accepting that sim will then
#       believe in torque the motors do not have.
# We keep the real 2.5/7.5 Nm here so sim2real is not silently optimistic. Revisit
# before expecting expressive head or forearm motion.
B1_ACTION_SCALE = {}
for a in B1_CFG.actuators.values():
    e = a.effort_limit_sim
    s = a.stiffness
    names = a.joint_names_expr
    if not isinstance(e, dict):
        e = dict.fromkeys(names, e)
    if not isinstance(s, dict):
        s = dict.fromkeys(names, s)
    for n in names:
        if n in e and n in s and s[n]:
            B1_ACTION_SCALE[n] = 0.25 * e[n] / s[n]
